# CI for openseaChest_LogParser
language: cpp

branches:
  only:
  - master
  - develop

matrix:
  include:
    - os: osx
      compiler: clang
      before_script: 
        cd Make/gcc
      script: 
        make farm && make clean_all && make release
    - os: linux
      sudo: false
      compiler:
        - gcc
        - clang
      dist: xenial
      before_script: 
        cd Make/gcc
      script: 
        make farm && make clean_all && make release
    - os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      before_script: 
        cd "Make\VS.2017\openSeaChest_LogParser\openSeaChest_LogParser"
      script: 
        - export PATH=$MSBUILD_PATH:$PATH 
        - MSBuild.exe //p:Configuration=Static-Release //p:Platform=x64

