# SPDX-License-Identifier: MPL-2.0
name: C/C++ CI

on:
  push:
    branches: [ develop, master, release/*, feature/*, hotfix/* ]
  pull_request:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: recursive
        
    - name: Cache build
      uses: actions/cache@v3.3.2
      with:
        path: Make/gcc/build
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-    

    - name: Build project
      run: |
        cd Make/gcc
        make farm && make clean_all && make release
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: release-build
        path: Make/gcc/release    
