name: C/C++ CI

on:
  push:
    branches: [ develop, master, release/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: make
      run: |
        cd Make/gcc
        make farm && make clean_all && make release
